# Basic
title: ä½•æ™“å³°
subtitle: ä¸ªäººç«™
description: æ¬¢è¿æ¥åˆ°æˆ‘çš„ä¸ªäººç«™~
# å¤´åƒé‡Œé¢çš„æ ‡é¢˜
avatarTitle: suifeng
# å¤´åƒé‡Œé¢çš„æè¿°
avatarDesc: è®¡ç®—æ•°å­¦ / æœºå™¨å­¦ä¹ 
url: "https://suifeng2020.github.io/"

# åšå®¢æ˜¯å¦è‡ªåŠ¨ç”Ÿæˆç›®å½•ï¼Œfalseä¸ºä¸ç”Ÿæˆ
enableToc: false

# Comment
comment:
    # livere: MTAyMC81MDk5NC8yNzQ3Ng  # https://www.livere.com
    # disqus: leopard
    # uyan: 2143225  # æœ‰è¨€id,ç™»å½•æœ‰è¨€å®˜ç½‘ç”³è¯·

# Social
social:
    #weibo: 5366874726 
    github: SuiFeng2020
    # zhihu: panpanleopard
    # juejin: xxx
    # jianshu: 2ada30d8d0f7
    # twitter: 
    mail: hexf@std.uestc.edu.cn


# ç™¾åº¦ç»Ÿè®¡ 
# ä½¿ç”¨åšå®¢æ¨¡æ¿è¯·å»æ‰æˆ–è€…æ›´æ¢ id 
baidu:
    id: 3f7adb99f2b3a0739d412afe1b5b23ce




# ã€Š----------------- ä¸Šé¢çš„ä¿¡æ¯ä¿®æ”¹æˆä½ è‡ªå·±çš„ ---------------------------ã€‹
#
#
#  _post/ ä¸‹çš„æ–‡ç« æ›´æ¢æˆä½ è‡ªå·±çš„æ–‡ç« 
#  å¸®å¿™starä¸€ä¸‹ï¼Œæ„Ÿè°¢~ğŸ˜† åœ°å€ï¼š https://github.com/leopardpan/leopardpan.github.io
#
#
# ã€Š--------------- ä¸‹é¢çš„ä¿¡æ¯å¯ä»¥è‡ªè¡Œé€‰æ‹©æ˜¯å¦ä¿®æ”¹ ------------------------ã€‹


permalink: /:year/:month/:title/
# Format
highlighter: rouge

textColor: #FF0000

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: clear

# The blog button should not be removed.
blog_button:
    title: åšå®¢ä¸»é¡µ

# Navigation buttons in the front page.s
nav:
    - {title: æ‰€æœ‰æ–‡ç« , description: archive, url: '/archive'}   
    - {title: æ ‡ç­¾, description: tags, url: '/tags'}        
    - {title: å…³äºæˆ‘, description: about, url: '/about'}   
    

# Pagination
gems: [jekyll-paginate,jekyll-sitemap]
paginate: 20
paginate_path: "page/:num/"

# LaTeX
# markdown: kramdown